// Dans src/context/LanguageContext.jsx

const translations = {
    fr: {
      // --- MENU / SIDEBAR ---
      nav_dashboard: "Tableau de bord",
      nav_program: "Mon Programme",
      nav_workouts: "Séances",
      nav_diet: "Nutrition",
      nav_profile: "Profil",
      nav_settings: "Paramètres",
      nav_logout: "Déconnexion",

      // --- DASHBOARD (Déjà fait) ---
      greeting: 'Bonjour,',
      athlete: 'Athlète',
      profile: 'Mon Profil',
      completed: '✅ TERMINÉE',
      todaysWorkout: '🔥 SÉANCE DU JOUR',
      minutes: 'minutes',
      exercises: 'exercices',
      several: 'Plusieurs',
      goodJob: 'Bon travail ! Reposez-vous.',
      startWorkout: 'Commencer l\'entraînement',
      restDay: 'Repos aujourd\'hui',
      restDesc: 'Pas de séance prévue.',
      noProgramDesc: 'Aucun programme actif.',
      createProgram: '+ Créer un programme',
      thisWeek: 'Cette Semaine',
      activeProgram: 'Programme Actif',
      minPerSession: 'min / séance',
      viewProgram: 'Voir le programme →',
      noProgram: 'Aucun programme',
      start: 'Commencer',
      quickMenu: 'Menu Rapide',
      aiGenerator: 'Générateur IA',
      analytics: 'Analytics',
      aiCoach: 'Coach IA',
      history: 'Historique',

      // --- BOUTONS COMMUNS ---
      save: "Enregistrer",
      cancel: "Annuler",
      edit: "Modifier",
      delete: "Supprimer",
      loading: "Chargement...",
      back: "Retour",
    },
    en: {
      // --- MENU / SIDEBAR ---
      nav_dashboard: "Dashboard",
      nav_program: "My Program",
      nav_workouts: "Workouts",
      nav_diet: "Nutrition",
      nav_profile: "Profile",
      nav_settings: "Settings",
      nav_logout: "Logout",

      // --- DASHBOARD ---
      greeting: 'Hello,',
      athlete: 'Athlete',
      profile: 'My Profile',
      completed: '✅ COMPLETED',
      todaysWorkout: '🔥 TODAY\'S WORKOUT',
      minutes: 'minutes',
      exercises: 'exercises',
      several: 'Several',
      goodJob: 'Good job! Rest up.',
      startWorkout: 'Start Workout',
      restDay: 'Rest Day',
      restDesc: 'No workout scheduled.',
      noProgramDesc: 'No active program.',
      createProgram: '+ Create Program',
      thisWeek: 'This Week',
      activeProgram: 'Active Program',
      minPerSession: 'min / session',
      viewProgram: 'View program →',
      noProgram: 'No program',
      start: 'Start',
      quickMenu: 'Quick Menu',
      aiGenerator: 'AI Generator',
      analytics: 'Analytics',
      aiCoach: 'AI Coach',
      history: 'History',

      // --- COMMON BUTTONS ---
      save: "Save",
      cancel: "Cancel",
      edit: "Edit",
      delete: "Delete",
      loading: "Loading...",
      back: "Back",
    }
  };